export default {
    ADD_TO_CART: 'ADD_TO_CART',
    UPDATE_CART: 'UPDATE_CART',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
    UPDATE_CURRENCY: 'UPDATE_CURRENCY',
    UPDATE_ITEMS_CART: 'UPDATE_ITEMS_CART',
};
